name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: SophiaSilveira
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Setup Pages
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for the gh-pages branch

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output

      - name: Debug Information
        run: |
          echo "Checking if SVG was generated"
          ls -la dist/
          echo "Contents of generated SVG file:"
          cat dist/github-contribution-grid-snake.svg
